### PR TITLE
Rspec tests for my Enumerable module

### PR DESCRIPTION
**Pull request by tigamadou**

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi Amadou!     image  
### Wow your Enumerable methods pass all your tests  



But few things to fix 





#### You can read here [let Blocks](https://github.com/rubocop-hq/rspec-style-guide#let-blocks)

### Additional Microverse Requirements 

#### General

* [ ] Pull Request has meaningful title and a short description

 screenshot from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
* [ ] Commits are descriptive

 screenshot from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Make changes and submit another code review request.


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
Happy coding

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
Project needs changes

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @genzaraki, 👋 You have done a good job in this project 👏 



----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by tigamadou** [comment]
@imhta @Anna-Myzukina Thank you, guys. :muscle:

**Pull request merged**
